#!/bin/bash

SSHDEV_HOST=mr-10 \
SSHDEV_REM_PROJ_DIR=/root/workspace/remote-trunk \
SSHDEV_LOC_ROOT_DIR=/home/jenia/mnt/mr-10 \
SSHDEV_LOC_PROJ_DIR=/home/jenia/mnt/mr-10/root/workspace/remote-trunk \
/opt/eclipse/eclipse &



exit 0

ssh-copy-id HOST

ssh-mount HOST

-----------------------------------------------------------
BUILD
-----------------------------------------------------------
HOST name must be deduced from mount path
ssh HOST "cd PROJDIR ; scons TARGET"

-----------------------------------------------------------
DEBUG
-----------------------------------------------------------
ssh HOST gdbserver host:1234 /opt/cods/bin/MrStreamManager 

(gdb) target remote mr-10:1234
(gdb) set sysroot /home/jenia/mnt/mr-10/
(gdb) continue

in .gdbinit
set sysroot /home/jenia/mnt/mr-10/
set substitute-path /root /home/jenia/mnt/mr-10/root
